version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn-install
          command: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "/tmp/reports/js-test-results.xml"
      - run:
          name: flow
          command: yarn flow
      - run:
          name: build
          command: yarn build
      - store_artifacts:
          path: /tmp/reports
      - store_test_results:
          path: /tmp/reports
